name: Deploy To Windows Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on:
      - self-hosted
      - windows
      - anti

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run deployment script on server
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          & "${{ github.workspace }}\scripts\deploy-windows.ps1"
